### ISSUE TITLE
if you try to clear the bench while holding an ingredient he resets back to idle

### ISSUE THREAD

**Issue by ju-de** [jz-feng/shiba-cafe#15]
![image](https://user-images.githubusercontent.com/7605884/118418240-7cb6a580-b66c-11eb-8413-b87a3f51fcc9.png)

**Comment by jz-feng** [comment]
fixing for now by not allowing clear bench while holding something. might come back to adjust this behavior later after we implement picking items back up from bench

**Comment by jz-feng** [comment]
#36
