### ISSUE TITLE
last letter typed carries over to next textinput

### ISSUE THREAD

**Issue by ju-de** [jz-feng/shiba-cafe#2]
![image](https://user-images.githubusercontent.com/7605884/118408532-d69e7780-b63a-11eb-9062-a005fa4202f8.png)
![image](https://user-images.githubusercontent.com/7605884/118408542-e1f1a300-b63a-11eb-9f08-32ec76876c29.png)

**Comment by ju-de** [comment]
mitigated for now by using word instead of letter selectors for actions, but should fix this eventually

**Comment by ju-de** [comment]
![image](https://user-images.githubusercontent.com/7605884/118413358-c6df5d00-b653-11eb-9d82-4ab313653b63.png)

double letter words are also affected

**Comment by jz-feng** [comment]
bad event ordering
```
inputs.type()
=> inputs[0].type()
  => EVENT_COMPLETE
  => inputs.reset()
    => input[0].reset()
    => input[1].reset()
    => ...
=> inputs[1].type()
=> ...
```

**Comment by jz-feng** [comment]
#43 lazy non-generalized fix but it works
